model:
  init_args:
    augmentations:
      - name: RandomResizedCrop
        init_args:
          size: [224, 224]
      - name: RandomHorizontalFlip
        init_args:
          p: 0.5
      - name: RandomVerticalFlip
        init_args:
          p: 0.5
