run_name: DynamicWorld

trainer:
  max_epochs: 100
  log_every_n_steps: 10
  callbacks:

model:
  class_path: geosave_engine.ml.tasks.SemanticSegmentationTask
  init_args:
    stages:
      encoder: dinov3
      decoder: dpt
      head: dense
    optimizer: AdamW.split
    scheduler: CosineAnnealingLR
    loss: CELoss
    config:
      encoder:
      optimizer:
        weight_decay: 0.01
        encoder_lr: 0.0001
        decoder_lr: 0.001
      scheduler:
        T_max: 100
    threshold_calibration_config:
      metric: f1

data:
  class_path: geosave_engine.ml.tasks.SemanticSegmentationDataModule
  init_args:
    train_root: data/test_pipeline/train
    val_root: data/test_pipeline/val
    test_root: data/test_pipeline/test
    batch_size: 2
    num_workers: 4
    sel_bands:
      sentinel_2_l1c: ["B04", "B03", "B02"]  # RGB
    dtype_override:
      sentinel_2_l1c: torch.float32
      cloud_mask: torch.bool
      dynamicworld: torch.int64
    pipeline:
      class_path: modules.data_pipeline.Pipeline
